### ISSUE TITLE
Including DateTime::Format::Strptime increases the running time by 100ms

### ISSUE THREAD

**Issue by LukeButters** [houseabsolute/DateTime-Format-Strptime#24]
Hi it looks like adding 
```
use DateTime::Format::Strptime;
```
increases the running time by an extra 100ms.

**Comment by preaction** [comment]
Thanks for the report! Is there anything you can recommend be done about this issue?

Did you try running your code under [Devel::NYTProf](https://metacpan.org/pod/Devel::NYTProf) to see which part of DateTime::Format::Strptime takes too long to load? I don't think that'll get into how long it takes `perl` to read the file and parse it, but it should show how long it takes to run the initialization code in the module.

100ms during startup is not really an incredible amount, so unless there's some obvious performance problem, this isn't really a workable request. The only thing I can even think of is doing lazy evaluation of the validators to avoid paying for validations that aren't used, but I'm not sure the increased code complexity is worth the minimal performance improvement.

**Comment by LukeButters** [comment]
Ok I ran that, it was super simple :D

[nytprof.out.zip](https://github.com/houseabsolute/DateTime-Format-Strptime/files/3193113/nytprof.out.zip)
[nytprof.zip](https://github.com/houseabsolute/DateTime-Format-Strptime/files/3193115/nytprof.zip)

I would argue that 100ms is actually quite a lot of time, I would prefer my pages (perl .cgi) to be returning in under 100ms. This is running on a 4Ghz cpu so I imagine when running on a  2Ghz epyc server chip that bumps up 200ms :'(. Users will definitely appreciate not waiting an extra 200ms on every page.

**Comment by autarch** [comment]
Generally speaking I've aimed to optimize the DateTime module family for runtime speed over compilation speed. The change that slowed down DT::F::Strptime was to switch to Params::ValidationCompiler a while back, but from my testing I've found that this module has much better runtime performance than Params::Validate.

I don't see a good way to optimize for both compile _and_ runtime performance (without giving up on parameter validation entirely). If you have an idea on that I'd be happy to hear that. For now I'm going to close this issue, since it's basically a "wontfix" as is.

**Comment by LukeButters** [comment]
No worries, I added lazy loading of the module so now at least all of the pages that don't need it don't need to wait for it.

For reference I remove the `use` and in the sub I needed to use this module I added:
```
require DateTime::Format::Strptime;
require DateTime::Format::ISO8601;
```

**Comment by autarch** [comment]
That seems like a good solution for CGI scripts.

**Comment by LukeButters** [comment]
oh cool, thanks for following up on this ticket.
